prompt Installing Jumbo Prime content model...

create table jp_benefit (
  benefit_key   varchar2(50 char)   not null,
  eyebrow       varchar2(120 char)  not null,
  title         varchar2(200 char)  not null,
  summary       varchar2(1000 char) not null,
  display_order number              default 10 not null,
  active_yn     char(1 char)         default 'Y' not null,
  created_at    timestamp with local time zone default systimestamp not null,
  updated_at    timestamp with local time zone default systimestamp not null,
  constraint jp_benefit_pk primary key (benefit_key),
  constraint jp_benefit_active_ck check (active_yn in ('Y', 'N'))
);

create table jp_benefit_logo (
  logo_id       number generated by default as identity,
  benefit_key   varchar2(50 char)  not null,
  file_path     varchar2(255 char) not null,
  alt_text      varchar2(200 char) not null,
  display_order number             default 10 not null,
  constraint jp_benefit_logo_pk primary key (logo_id),
  constraint jp_benefit_logo_benefit_fk
    foreign key (benefit_key) references jp_benefit (benefit_key) on delete cascade,
  constraint jp_benefit_logo_uq unique (benefit_key, display_order)
);

create table jp_benefit_item (
  item_id       number generated by default as identity,
  benefit_key   varchar2(50 char)   not null,
  item_text     varchar2(500 char)  not null,
  display_order number              default 10 not null,
  constraint jp_benefit_item_pk primary key (item_id),
  constraint jp_benefit_item_benefit_fk
    foreign key (benefit_key) references jp_benefit (benefit_key) on delete cascade,
  constraint jp_benefit_item_uq unique (benefit_key, display_order)
);

create table jp_offer (
  offer_id      number generated by default as identity,
  offer_key     varchar2(50 char)   not null,
  eyebrow       varchar2(120 char)  not null,
  title         varchar2(200 char)  not null,
  summary       varchar2(1000 char) not null,
  image_path    varchar2(255 char),
  image_alt     varchar2(255 char),
  visual_value  varchar2(40 char),
  visual_label  varchar2(80 char),
  action_label  varchar2(80 char)   not null,
  action_url    varchar2(1000 char) not null,
  display_order number              default 10 not null,
  active_yn     char(1 char)         default 'Y' not null,
  created_at    timestamp with local time zone default systimestamp not null,
  updated_at    timestamp with local time zone default systimestamp not null,
  constraint jp_offer_pk primary key (offer_id),
  constraint jp_offer_key_uq unique (offer_key),
  constraint jp_offer_active_ck check (active_yn in ('Y', 'N'))
);

create table jp_faq (
  faq_id        number generated by default as identity,
  question      varchar2(500 char)  not null,
  answer        varchar2(2000 char) not null,
  display_order number              default 10 not null,
  active_yn     char(1 char)         default 'Y' not null,
  created_at    timestamp with local time zone default systimestamp not null,
  updated_at    timestamp with local time zone default systimestamp not null,
  constraint jp_faq_pk primary key (faq_id),
  constraint jp_faq_order_uq unique (display_order),
  constraint jp_faq_active_ck check (active_yn in ('Y', 'N'))
);

create index jp_benefit_order_ix on jp_benefit (active_yn, display_order);
create index jp_offer_order_ix on jp_offer (active_yn, display_order);
create index jp_faq_order_ix on jp_faq (active_yn, display_order);

create or replace trigger jp_benefit_bu
before update on jp_benefit
for each row
begin
  :new.updated_at := systimestamp;
end;
/

create or replace trigger jp_offer_bu
before update on jp_offer
for each row
begin
  :new.updated_at := systimestamp;
end;
/

create or replace trigger jp_faq_bu
before update on jp_faq
for each row
begin
  :new.updated_at := systimestamp;
end;
/

comment on table jp_benefit is 'Beneficios publicados en la landing Jumbo Prime.';
comment on table jp_offer is 'Promociones visibles en el carrusel de Jumbo Prime.';
comment on table jp_faq is 'Preguntas frecuentes publicadas en la landing.';

prompt Jumbo Prime content model installed.
